### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by KaKi87** [zenparsing/zen-observable#59]
Hello,

I'm currently coding a microframework for Discord (command handler, etc.)

And I've got this error :

```
TypeError: Cannot read property 'call' of undefined
    at new Subscription (C:\TEMP\ig-bot\node_modules\zen-observable\lib\Observable.js:183:34)
    at CommandHandler.subscribe (C:\TEMP\ig-bot\node_modules\zen-observable\lib\Observable.js:262:14)
    at Object.<anonymous> (C:\TEMP\ig-bot\index.js:21:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
```

Here's my code : https://git.kaki87.net/KaKi87/discord-microframework
(More precisely here : https://git.kaki87.net/KaKi87/discord-microframework/src/branch/master/lib/CommandHandler.js)

The error is triggered when `Observable.subscribe` is fired and I tried to identify the issue, for days, but I can't find out.

Thanks !!

**Comment by zenparsing** [comment]
Hi @KaKi87!

It looks like you are pulling out the `subscribe` method of an observable and attaching it to a different object (a CommandHandler instance). The problem is that, in JS, when you pull out a method it loses the correct "this" value.

```js
class X {
  constructor() { this.a = 1; }
  hello() { console.log(this.a); }
}

new X().hello(); // 1

let hello = new X().hello;

hello(); // Throws an error, because "this" is undefined
```

You might want to do something like:

```js
class CommandHandler {
  constructor() {
    this._observable = new Observable(...);
  }

  subscribe(...args) {
    return this._observable.subscribe(...args);
  }
}
```

**Comment by KaKi87** [comment]
I understand, thanks !
